### ISSUE TITLE
Second pass of `metadata.yml` scaffolding

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#1428]
Hoping to get a second pass of `metadata.yml` scaffolding generated from code. 
- [ ] Populate variant names. Currently the file contains mentions of the main icon, eg. Add, but no add--alt. Ideally we can add all the available variants of an icon too in the scaffold
- [ ] Populate file sizes. 

So in below example, only fields need to be manually filled are `friendly_name`, `usage`, `categories`, and `aliases`. 

```yml
- name: add
    friendly_name: Add
    usage: This is a description for usage
    categories:
      - Navigation
    aliases:
      - add
      - plus
      - cross
      - create
    sizes:
      - 16
      - 32
    variants:
      - name: add--alt
        usage: This is a description for usage
        sizes:
          - 16
          - 32
      - name: add--filled
        usage: This is a description for usage
        sizes:
          - 16
```
