### ISSUE TITLE
GlossaryNav list padding is breaking the List component demo

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon-website#1857]
## Detailed description

These styles in for the `GlossaryNav` (specifically, `padding: 0`)
```scss
.bx--list__item {
  list-style-type: none !important;
  padding: 0;
  width: 100%;
  transition: all $transition--base;
  display: block;
}
```

https://github.com/carbon-design-system/carbon-website/blob/master/src/components/GlossaryNav/glossary-nav.scss#L22

.. are breaking the `List` component demo: https://www.carbondesignsystem.com/components/list/code

![Screen Shot 2019-08-01 at 2 59 31 PM](https://user-images.githubusercontent.com/9057921/62323475-fc11bf80-b46c-11e9-9421-f324a247dae3.png)

If you comment-out the `padding: 0` line, then the list in the component demo looks good 👍
