### ISSUE TITLE
Tutorial step 2 grid left right padding

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#2040]
![image](https://user-images.githubusercontent.com/1691245/101526914-ed85c300-3952-11eb-8195-a877239c4cde.png)

Notice the white gap to the left and right of the gray background in the tutorial header. Grid has 2.5rem left and right padding at 99rem breakpoint. Is that new? I don't see that in the preview.

![image](https://user-images.githubusercontent.com/1691245/101527068-2887f680-3953-11eb-83a5-7aa1cb7461ae.png)

Updating this to spacing-06 looks to fix it.

```scss
@mixin landing-page-background() {
  background-color: $ui-01;
  position: relative;

  &::before {
    content: '';
    position: absolute;
    left: -$spacing-06;
    top: 0;
    right: -$spacing-06;
    bottom: 0;
    background: $ui-01;
    z-index: -1;
  }
}
```

CC @alisonjoseph @tw15egan
