### ISSUE TITLE
Invalid color hex in ComponentDemo SCSS

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon-website#2280]
Related #1035

Invalid color hexes in `ComponentDemo.module.scss` are causing lint errors

```scss
[class*='--data-table--zebra'] tbody tr:nth-child(odd) td {
  background-color: var(--cds-ui-02, #fffff);
  border-bottom: var(--cds-ui-02, #fffff);
  border-top: var(--cds-ui-02, #fffff);
}
```
