### ISSUE TITLE
docs(2x-grid): update with breakpoints api

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3108]
### Summary

The website needs to show how the `breakpoint` API works. This is mostly a content design thing, but also UX and dev need to be in the room.

### Justification

Closes https://github.com/carbon-design-system/carbon/issues/10687

### Desired UX and success metrics

An Carbon maker should be able to visit the 2x Grid page and leave with a full comprehension of the breakpoint API.

### Must-have functionality

Using our `breakpoint` [mixins](https://github.com/carbon-design-system/carbon/blob/ff7418e115708635cf4936b6e7f999824af1bc57/packages/layout/scss/_breakpoint.scss#L134-L243) to add styles (hide or show components) for different breakpoints. Something like:

```css

.component {
    display: inline;

    /* applies styles inside mixin on md breakpoint or below, like max-width */
    @include carbon--breakpoint-down('md') {
        display: none; 
    }
}
```

the breakpoint mixins include:
- `carbon--breakpoint-down()`
- ` carbon--breakpoint-up()` || `breakpoint()`
- `carbon--breakpoint-between()` this takes 2 args, to apply styles in between 2 breakpoints i.e. md - lg
- `carbon--largest-breakpoint()`
